version: '3'

services:

  service:
    container_name: streaming-candle-bybit
    build: ./
    restart: always
    env_file: ./.env
    command: ["poetry", "run", "python", "app/bybit/main.py"]
    deploy:
      resources:
        limits:
          cpus: '0.25'
        reservations:
          cpus: '0.15'
    networks:
      - GLOBAL_NETWORK

volumes:
  redis-data:

networks:
  GLOBAL_NETWORK:
    external: true