version: '3'

services:

  service:
    container_name: streaming-candle
    build: ./
    restart: always
    env_file: ./.env
    deploy:
      resources:
        limits:
          cpus: '0.25'
        reservations:
          cpus: '0.15'
    networks:
      - GLOBAL_NETWORK


volumes:
  redis-data:

networks:
  GLOBAL_NETWORK:
    external: true