name: Deploy to PRODUCTION Server


on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      #----------------------------------------------
      # Определяем хосты
      #----------------------------------------------
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      #----------------------------------------------
      # Подключение к серверу и пересборка проекта
      #----------------------------------------------
      - name: Connect to server> .env

        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            sudo rm -rf apps/STREAMS
            sudo mkdir apps/STREAMS
            cd apps/STREAMS
            
            script: |
            # Попытка клонирования репозитория
            if ! sudo git clone https://username:${{ secrets.ACCESS_TOKEN }}@github.com/pyostr-traiding/streams.git .; then
              echo "Ошибка при клонировании репозитория"
              exit 1
            fi
      
            # Установка .env файла
            if ! echo "${{ secrets.ENV_FILE }}" > .env; then
              echo "Ошибка при установке .env файла"
              exit 1
            fi
      
            # Попытка запуска docker-compose
            if ! docker compose up --build -d; then
              echo "Ошибка при запуске docker-compose"
              exit 1
            fi
